#!/bin/sh

. ${MODULESHOME}/init/sh
module load git

export SHiELD_SRC=${PWD%/*}/SHiELD_SRC/

mkdir -p ${SHiELD_SRC}
cd ${SHiELD_SRC}

release="test"
fms_release="2021.03"
fv3_release="test2"
phy_release="system_update"

git clone -b ${fv3_release}  https://gitlab.gfdl.noaa.gov:Rusty.Benson/atmos_cubed_sphere.git
git clone -b ${phy_release}  https://gitlab.gfdl.noaa.gov/Rusty.Benson/fv3_gfsphysics.git
git clone -b ${fms_release}  https://github.com/NOAA-GFDL/FMS

#Automatic release tracking from Matt M.
echo $release > ../../release
