#!/bin/sh

#
# set up some default variables for use within the script
BUILD_ROOT=${PWD%/*}
SHiELD_SRC=${PWD%/*/*}/SHiELD_SRC
PATH="${BUILD_ROOT}/mkmf/bin:${PATH}"

#
# get the correct system environment
. ${BUILD_ROOT}/site/environment.sh

#
# CPPDEFS needed to build libFMS
cppDefs="-Duse_libMPI -Duse_netCDF -Duse_LARGEFILE -DHAVE_SCHED_GETAFFINITY -DINTERNAL_FILE_NML -DGFS_PHYS"

#
# clean up and create the FMS library directory
pushd ../Build/
\rm -rf libFMS

#########################
#---CREATE 32-BIT libFMS
#########################
bit="32bit"
mkdir -p libFMS/${bit}
pushd libFMS/${bit}
(cd ${SHiELD_SRC} ; list_paths -o ${BUILD_ROOT}/Build/libFMS/${bit}/pathnames_fms FMS)
mkmf -m Makefile -a ${SHiELD_SRC} -t "${BUILD_ROOT}/${TEMPLATE}" -c "$cppDefs" \
     -p libFMS.a ${BUILD_ROOT}/Build/libFMS/${bit}/pathnames_fms
echo "building libFMS/32bit/libFMS.a..."
make -j8 OPENMP=Y AVX=Y 32BIT=Y Makefile libFMS.a >& Build_libFMS.out

#
# test and report on build success
if [ $? -ne 0 ] ; then
   echo " ${bit} build failed "
   exit 1
fi

#
# return to the root directory
popd

#########################
#---CREATE 64-BIT libFMS
#########################
bit="64bit"
mkdir -p libFMS/${bit}
pushd libFMS/${bit}
(cd ${SHiELD_SRC} ; list_paths -o ${BUILD_ROOT}/Build/libFMS/${bit}/pathnames_fms FMS)
mkmf -m Makefile -a ${SHiELD_SRC} -t "${BUILD_ROOT}/${TEMPLATE}" -c "$cppDefs" \
     -p libFMS.a ${BUILD_ROOT}/Build/libFMS/${bit}/pathnames_fms
echo "building libFMS/64bit/libFMS.a..."
make -j8 OPENMP=Y AVX=Y Makefile libFMS.a >& Build_libFMS.out

#
# test and report on build success
if [ $? -ne 0 ] ; then
   echo " ${bit} build failed "
   exit 1
fi

echo "Build of libfms_32bit.a and libfms_64bit.a successful"
popd
popd
ln -sf ../Build/libFMS .
exit 0
