#!/bin/sh

set -o xtrace


#
## set default values
HYDRO="nh"
BIT="32bit"

#
### parse arguments
for arg in "$@"
do
    case $arg in
        nh|hydro|sw)
        HYDRO="${arg#*=}"
        shift # Remove HYDRO from processing
        ;;
        32bit|64bit)
        BIT="${arg#*=}"
        shift # Remove *bit from processing
        ;;
        prod|repro|debug)
        COMP="${arg#*=}"
        shift 
        ;;
    esac
done

#
# FV3 CPPDEFS
#FV3_cppDefs="-DDYCORE_SOLO -Duse_libMPI -Duse_netCDF -DHAVE_SCHED_GETAFFINITY -DSPMD -DUSE_LOG_DIAG_FIELD_INFO -Duse_LARGEFILE -DNO_CMIP_DIAG -DINTERNAL_FILE_NML" #get_affinity doesn't work
FV3_cppDefs="-DDYCORE_SOLO -Duse_libMPI -Duse_netCDF -DSPMD -DUSE_LOG_DIAG_FIELD_INFO -Duse_LARGEFILE -DNO_CMIP_DIAG -DINTERNAL_FILE_NML -DDCMIP -DHIWPP"

#
# non-hydrostatic CPPDEFS
if [ ${HYDRO} = "nh" ] ; then
  FV3_cppDefs="${FV3_cppDefs} -DMOIST_CAPPA -DUSE_COND"
fi

if [ ${HYDRO} = "sw" ] ; then
    FV3_cppDefs="${FV3_cppDefs} -DSW_DYNAMICS -DDYNAMICS_ZS"
fi

pushd exec/

############################
#---CREATE MAKEFILES
############################
mkmf -m Makefile_solo -a ${SHiELD_SRC} -t "${BUILD_ROOT}/${TEMPLATE}" -c "${FV3_cppDefs}" -o "-I${SHiELD_SRC}/FMS/include -I${BUILD_ROOT}/Build-solo/libFMS/${BIT}" -p test.x ${BUILD_ROOT}/Build-solo/exec/pathnames_solo

############################
#---ADD LIBS TO FINAL LINK
############################
sed 's/LDFLAGS/NCEPLIBS) $(LDFLAGS/g' < Makefile_solo > OUT
mv OUT Makefile_solo

############################
#---ADD FAST TRANSCENDENTALS
#---model/nh_utils.F90
#---model/fv_mapz.F90
############################
sed 's"$(FC) $(CPPDEFS) $(FPPFLAGS) $(FFLAGS) $(OTHERFLAGS) $(OTHER_FFLAGS) -c\t$(SRCROOT)atmos_cubed_sphere/model/nh_utils.F90"$(FC) $(CPPDEFS) $(FPPFLAGS) $(FFLAGS) $(OTHERFLAGS) $(OTHER_FFLAGS) $(FAST) -c\t$(SRCROOT)atmos_cubed_sphere/model/nh_utils.F90"' < Makefile_solo > OUT
mv OUT Makefile_solo

sed 's"$(FC) $(CPPDEFS) $(FPPFLAGS) $(FFLAGS) $(OTHERFLAGS) $(OTHER_FFLAGS) -c\t$(SRCROOT)atmos_cubed_sphere/model/fv_mapz.F90"$(FC) $(CPPDEFS) $(FPPFLAGS) $(FFLAGS) $(OTHERFLAGS) $(OTHER_FFLAGS) $(FAST) -c\t$(SRCROOT)atmos_cubed_sphere/model/fv_mapz.F90"' < Makefile_solo > OUT
mv OUT Makefile_solo

############################

popd

exit 0
